spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "c9kdtZ4l6AgUTt1OOtC5aetX+FwlaQtj92exzbwm28oMiOarjk4Twk7rrBikc8B7"
    username: "1JQrJLS5kCF2sbM9L3mT5w=="
    password: "kzFgh/OxvV8sA6UPnmKRiw=="
  http:
    encoding:
      charset:    UTF-8
  mvc:
    view:
      prefix:     /jsp/
      suffix:     .jsp
  # oauth2 setting
  security:
    oauth2:
      client:
        registration:
          # facebook app info
          facebook:
            client-id: 653518488403585
            client-secret: 1d38225adfc60eb7c761415df5ada18c
          # google app info
          google:
            client-id: 608512517046-p3fde6e9o2nfvaucprg1efhlnfa248dl.apps.googleusercontent.com
            client-secret: zhJsINj_YOWRPh5BoYrEa3Tl

# used sns
spring.social.auths: facebook,google
      
server:
  port : 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
    
mybatis:
  config-location: classpath:mybatis-config.xml

# App propertiese
app:
  jwtSecret: "JWTSuperSecretKey"
  jwtExpirationInMs: 604800000